#
##  Building angular app
#
FROM node:14.16 as builder

WORKDIR /usr/local/app

COPY ./ /usr/local/app/

RUN rm -rf node_modules/

RUN rm -rf dist/

RUN npm ci

RUN npm install -g --save-dev @angular/cli@latest

RUN npm run production --output-path=/dist

#
##  Running application using nginx
#
FROM nginx:latest

COPY --from=builder /usr/local/app/dist/binwise-web /usr/share/nginx/html

COPY ./nginx/nginx.conf /etc/nginx/nginx.conf

COPY ./ssl/certs /etc/ssl/certs

COPY ./ssl/private /etc/ssl/private

ENTRYPOINT ["nginx", "-g", "daemon off;"]
